### ISSUE TITLE
Failing to binde Port when IPv6 is disabled

### ISSUE THREAD

**Issue by bahamapascal** [bahamapascal/ICCR#11]
ICCR tries to bind to the port via IPv6. If IPv6 is disabled it will not fall back automatically to IPv4 but instead just fails to listen to the Port.

Error Log:
[ICCR PORT Error.txt](https://github.com/bahamapascal/ICCR/files/1201997/ICCR.PORT.Error.txt)

**Comment by ahab94** [comment]
@bahamapascal  we close this one!

**Comment by bahamapascal** [comment]
Yes, good Idea!
